#!/bin/bash
#
# generate-macos-setup.sh - Generate macOS post-installation .command script
# Author: Mario Aldayuz (thenotoriousllama)
# Website: https://aldayuz.com
#
# This script generates a .command file that automates macOS post-installation tasks
# including Homebrew, Python, Supporting Tools, Lilu, and VMHide installation.
#

set -e

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Source common functions
source "${SCRIPT_DIR}/scripts/lib/common-functions.sh"

# Set log file
LOG_FILE="${LOG_FILE:-${SCRIPT_DIR}/logs/generate-macos-setup.log}"
mkdir -p "$(dirname "$LOG_FILE")" 2>/dev/null || true

# Default values
OUTPUT_FILE=""
SERIAL_NUMBER=""

#
# parse_arguments() - Parse command line arguments
#
parse_arguments() {
    while [ $# -gt 0 ]; do
        case "$1" in
            --output)
                OUTPUT_FILE="$2"
                shift 2
                ;;
            --serial)
                SERIAL_NUMBER="$2"
                shift 2
                ;;
            --help|-h)
                echo "Usage: $0 --output <output_file> [--serial <serial>]"
                echo
                echo "Options:"
                echo "  --output <path>   Output file path for .command script (required)"
                echo "  --serial <serial> Serial number for comments (optional)"
                echo "  --help            Show this help message"
                exit 0
                ;;
            *)
                log_message "ERROR: Unknown option: $1"
                echo "Use --help for usage information" >&2
                exit 1
                ;;
        esac
    done
    
    # Validate required arguments
    if [ -z "$OUTPUT_FILE" ]; then
        log_message "ERROR: --output argument is required"
        exit 1
    fi
}

#
# generate_command_script() - Generate the .command script content
#
generate_command_script() {
    log_message "Generating macOS setup .command script..."
    
    # Create output directory if it doesn't exist
    local output_dir=$(dirname "$OUTPUT_FILE")
    if [ ! -d "$output_dir" ]; then
        mkdir -p "$output_dir" || {
            log_message "ERROR: Failed to create output directory: $output_dir"
            exit 1
        }
    fi
    
    # Generate the script
    cat > "$OUTPUT_FILE" << 'EOF'
#!/bin/bash
#
# Hackintoshster macOS Post-Installation Setup
# Auto-generated by Hackintoshster
# Website: https://aldayuz.com
#
# This script automates the installation of essential tools and kernel extensions
# for your Hackintosh VM.
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Log function
log_step() {
    echo -e "${BLUE}==>${NC} $1"
}

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}!${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

# Header
clear
echo "═══════════════════════════════════════════════════════════════"
echo "     Hackintoshster macOS Post-Installation Setup"
echo "═══════════════════════════════════════════════════════════════"
echo
EOF

    # Add serial number comment if provided
    if [ -n "$SERIAL_NUMBER" ]; then
        cat >> "$OUTPUT_FILE" << EOF
echo "System Serial: ${SERIAL_NUMBER}"
echo
EOF
    fi

    # Continue with the script
    cat >> "$OUTPUT_FILE" << 'EOF'

# Check if running as user (not root)
if [ "$EUID" -eq 0 ]; then
    log_error "Please run this script as a regular user (not with sudo)"
    echo "The script will prompt for sudo password when needed."
    exit 1
fi

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Step 1: Disable GateKeeper
#
log_step "Step 1: Disabling GateKeeper..."
echo "  This allows running unsigned applications and scripts"
echo "  Administrator password required..."

if sudo spctl --master-disable 2>/dev/null; then
    log_success "GateKeeper disabled successfully"
    
    # Verify status
    local gk_status=$(spctl --status 2>&1)
    echo "  Status: $gk_status"
else
    log_warning "Failed to disable GateKeeper (may already be disabled)"
fi

echo

#
# Step 2: Mount EFI Partition
#
log_step "Step 2: Mounting EFI partition..."

# Check if already mounted
if mount | grep -q "/dev/disk0s1"; then
    log_success "EFI partition is already mounted"
    MOUNT_POINT=$(mount | grep "/dev/disk0s1" | awk '{print $3}')
    echo "  Location: $MOUNT_POINT"
else
    # Create mount point
    echo "  Creating mount point /Volumes/EFI..."
    sudo mkdir -p /Volumes/EFI
    
    # Mount EFI partition
    echo "  Mounting /dev/disk0s1..."
    if sudo mount -t msdos /dev/disk0s1 /Volumes/EFI 2>/dev/null; then
        log_success "EFI partition mounted successfully"
        echo "  Location: /Volumes/EFI"
    else
        log_error "Failed to mount EFI partition"
        echo "  This may be normal if the EFI partition is formatted differently"
        echo "  Continuing without EFI mount..."
    fi
fi

echo

#
# Step 3: Copy Custom EFI Configuration from BOOT.img
#
log_step "Step 3: Installing custom EFI configuration..."

if [ ! -f "$SCRIPT_DIR/BOOT.img" ]; then
    log_warning "BOOT.img not found in ISO"
    echo "  Skipping EFI configuration copy"
else
    echo "  Mounting BOOT.img..."
    
    # Mount BOOT.img temporarily
    if hdiutil attach "$SCRIPT_DIR/BOOT.img" -readonly -mountpoint /tmp/boot_efi 2>/dev/null; then
        log_success "BOOT.img mounted"
        
        # Check if EFI partition is available
        if [ -d "/Volumes/EFI" ]; then
            # Backup existing EFI if present
            if [ -d "/Volumes/EFI/EFI" ]; then
                echo "  Backing up existing EFI configuration..."
                sudo mv "/Volumes/EFI/EFI" "/Volumes/EFI/EFI.backup.$(date +%Y%m%d_%H%M%S)" 2>/dev/null || true
            fi
            
            # Copy custom EFI with injected serial
            echo "  Copying custom EFI configuration..."
            if sudo cp -r /tmp/boot_efi/EFI /Volumes/EFI/ 2>/dev/null; then
                log_success "Custom EFI configuration installed"
                echo "  OpenCore config with your unique serial has been installed"
                
                # Verify
                if [ -f "/Volumes/EFI/EFI/OC/config.plist" ]; then
                    log_success "config.plist verified"
                fi
            else
                log_error "Failed to copy EFI configuration"
            fi
        else
            log_warning "EFI partition not mounted, skipping configuration copy"
        fi
        
        # Unmount BOOT.img
        hdiutil detach /tmp/boot_efi 2>/dev/null || true
    else
        log_warning "Failed to mount BOOT.img"
        echo "  Your EFI configuration is still available in the ISO"
    fi
fi

echo

#
# Step 4: Check and install Homebrew
#
log_step "Step 4: Checking for Homebrew..."

if command -v brew &> /dev/null; then
    log_success "Homebrew is already installed"
    BREW_PATH=$(which brew)
    echo "  Location: $BREW_PATH"
else
    log_step "Installing Homebrew..."
    echo "  This may take a few minutes..."
    
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    
    # Add Homebrew to PATH for Apple Silicon Macs
    if [ -d "/opt/homebrew/bin" ]; then
        export PATH="/opt/homebrew/bin:$PATH"
    fi
    
    if command -v brew &> /dev/null; then
        log_success "Homebrew installed successfully"
    else
        log_error "Homebrew installation failed"
        exit 1
    fi
fi

echo

#
# Step 5: Install Python3
#
log_step "Step 5: Checking for Python3..."

if command -v python3 &> /dev/null; then
    PYTHON_VERSION=$(python3 --version 2>&1)
    log_success "Python3 is already installed: $PYTHON_VERSION"
else
    log_step "Installing Python3 via Homebrew..."
    
    brew install python3
    
    if command -v python3 &> /dev/null; then
        PYTHON_VERSION=$(python3 --version 2>&1)
        log_success "Python3 installed: $PYTHON_VERSION"
    else
        log_error "Python3 installation failed"
        exit 1
    fi
fi

echo

#
# Step 6: Copy Supporting_Tools to Desktop
#
log_step "Step 6: Copying Supporting Tools to Desktop..."

DESKTOP_PATH="$HOME/Desktop"
SOURCE_TOOLS="$SCRIPT_DIR/Supporting_Tools"
DEST_TOOLS="$DESKTOP_PATH/Supporting_Tools"

if [ ! -d "$SOURCE_TOOLS" ]; then
    log_error "Supporting_Tools directory not found in ISO: $SOURCE_TOOLS"
    echo "  Make sure this script is run from the mounted ISO."
    exit 1
fi

if [ -d "$DEST_TOOLS" ]; then
    log_warning "Supporting_Tools already exists on Desktop, removing old version..."
    rm -rf "$DEST_TOOLS"
fi

cp -r "$SOURCE_TOOLS" "$DEST_TOOLS"

if [ -d "$DEST_TOOLS" ]; then
    log_success "Supporting Tools copied to Desktop"
else
    log_error "Failed to copy Supporting Tools"
    exit 1
fi

echo

#
# Step 7: System verification
#
log_step "Step 7: Running system verification..."
echo

# Check GateKeeper status
echo "GateKeeper Status:"
GK_STATUS=$(spctl --status 2>&1)
if [[ "$GK_STATUS" =~ "disabled" ]]; then
    log_success "GateKeeper: $GK_STATUS"
else
    log_warning "GateKeeper: $GK_STATUS"
fi

echo

# Check EFI mount status
echo "EFI Partition Status:"
if mount | grep -q "/dev/disk0s1"; then
    EFI_MOUNT=$(mount | grep "/dev/disk0s1" | awk '{print $3}')
    log_success "EFI mounted at: $EFI_MOUNT"
    
    # Check if custom config was installed
    if [ -f "$EFI_MOUNT/EFI/OC/config.plist" ]; then
        log_success "Custom OpenCore config installed"
    fi
else
    log_warning "EFI partition not mounted"
fi

echo

# Check Python
echo "Python Status:"
if command -v python3 &> /dev/null; then
    PYTHON_VER=$(python3 --version 2>&1)
    log_success "$PYTHON_VER"
else
    log_warning "Python3 not installed"
fi

echo

echo "Checking kernel extensions loaded by OpenCore:"
echo

# Check for essential kexts
KEXTS_TO_CHECK=("Lilu" "VMHide" "VirtualSMC" "WhateverGreen")

for kext in "${KEXTS_TO_CHECK[@]}"; do
    if kextstat | grep -q "$kext"; then
        log_success "$kext is loaded"
    else
        log_warning "$kext is not loaded"
    fi
done

echo
echo "CPU Information:"
sysctl -n machdep.cpu.brand_string

echo
echo "SMBIOS Information:"
ioreg -l | grep -E "board-id|IOPlatformSerialNumber" | head -2

echo
echo "═══════════════════════════════════════════════════════════════"
echo "                    Setup Complete!"
echo "═══════════════════════════════════════════════════════════════"
echo
log_success "GateKeeper disabled for unsigned applications"
log_success "Custom EFI configuration installed to boot disk"
log_success "All essential kernel extensions are loaded by OpenCore"
log_success "Supporting Tools are available on your Desktop"
echo
log_warning "NOTE: All required kexts are loaded from EFI/OC/Kexts"
log_warning "      Lilu, VMHide, VirtualSMC, WhateverGreen included in EFI"
echo
read -p "Press Enter to exit..."
EOF

    # Make the output file executable
    chmod +x "$OUTPUT_FILE"
    
    if [ $? -ne 0 ]; then
        log_message "ERROR: Failed to make output file executable"
        exit 1
    fi
    
    log_message "Successfully generated .command script: $OUTPUT_FILE"
    return 0
}

#
# main() - Main entry point
#
main() {
    parse_arguments "$@"
    generate_command_script
    
    log_message "macOS setup script generated successfully"
    exit 0
}

# Run main function
main "$@"

